
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tigerpup_development

test:
  <<: *default
  adapter: postgresql
  database: tigerpup_test

production:
  <<: *default
  database: tigerpup_production
  username: tigerpup
  password: <%= ENV['TIGERPUP_DATABASE_PASSWORD'] %>
